### ISSUE TITLE
Not all fields bound when adding a read book

### ISSUE THREAD

**Issue by knjk04** [knjk04/book-project#111] opened 2020-06-30 18:35 UTC
**Describe the bug**

Not all fields are stored when saving a book.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on 'add book'
2. Add a new book by filling in all the fields. Ensure the shelf is set to 'read'
3. See error

**Expected behaviour**

All fields should be bound.

**Screenshots**

![image](https://user-images.githubusercontent.com/11173328/86163620-71b45e80-bb08-11ea-9d8d-200e7a91128f.png)

**Additional context**

As this is a bug, a test(s) should be written to ensure this doesn't happen again in the future.

Also, it would be good if a [Vaadin notification](https://vaadin.com/components/vaadin-notification/) is shown to the user to confirm that a book has been saved (so that they don't need to switch to that bookshelf to check if they're currently in a different shelf).

Adding a book:

![image](https://user-images.githubusercontent.com/11173328/86163871-cf48ab00-bb08-11ea-8983-b21753a3d5b9.png)

Not all fields were stored

**Comment by kbohra** [comment] 2020-07-01 18:14
@knjk04 can you assign this issue to me ? I can take a look

**Comment by knjk04** [comment] 2020-07-01 19:08
Thanks!

For some additional context, I think this only happens when the app first loads

**Comment by knjk04** [comment] 2020-07-20 05:51
How are you getting on with this issue?

**Comment by knjk04** [comment] 2020-07-28 07:30
Since we haven't heard back from you in a while, I'm going to unassign you from the issue so that it is available for someone else to pick this up (as per our contributing guidelines). 

If you still wish to be assigned to this issue but need more time or any help, let us know and we can reassign you to the issue and help if necessary.

**Comment by tmrd993** [comment] 2020-08-06 17:30
I'll look into this but I don't want to be assigned (yet) as I don't have a lot of time this month. I just wanted to add that this also happens with other shelves, not just the read shelf. Also (like you said) it seems to only happen at startup and after a while (or after adding books?) it seems to work as intended.

**Comment by knjk04** [comment] 2020-08-06 18:17
Thanks, I've updated the issue description accordingly.

**Comment by tmrd993** [comment] 2020-08-10 06:55
Some more info:

This happens only when `binder.getBean()` returns null. Take a look at the validateOnSave() method in the BookForm class. I am not too familiar with Spring but in the setBookBean() method, you create a new Book object, extract some of the fields (I am guessing those are the required fields?) for the Book object and set the Book bean. The only parameters that get saved and show up on the shelf are the ones you extract in the setBookBean() method.

However, whenever `binder.getBean()` is **not null**, all fields are bound correctly. This usually happens after adding a single book.

**Comment by knjk04** [comment] 2020-08-10 08:48
Thanks a lot for this!

**Closed** 2020-08-10 09:52 UTC
Labels: bug, high-priority, vaadin
